#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include "lwip/pbuf.h"
#include "lwip/tcp.h"
#include "login.h"

extern char http_response[8192];
void create_cadastro_usuario_page(const char *mensagem_erro) {
    char bloco_erro[256] = "";

    if (mensagem_erro && strlen(mensagem_erro) > 0) {
        snprintf(bloco_erro, sizeof(bloco_erro),
                 "<div class=\"mensagem-erro\">%s</div>", mensagem_erro);
    }
    
    snprintf(http_response, sizeof(http_response),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=UTF-8\r\n\r\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"pt-BR\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Cadastro de Usuário</title>\n"
        "    <style>\n"
        "        body {\n"
        "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        "            background: linear-gradient(135deg, #f5f7fa 0%%, #c3cfe2 100%%);\n"
        "            margin: 0;\n"
        "            padding: 0;\n"
        "            color: #333333;\n"
        "        }\n"
        "        .container-administrador {\n"
        "            display: flex;\n"
        "            flex-direction: column;\n"
        "            min-height: 100vh;\n"
        "        }\n"
        "        .barra-navegacao {\n"
        "            background-color: #166088;\n"
        "            color: white;\n"
        "            padding: 0.8rem 1rem;\n"
        "            display: flex;\n"
        "            justify-content: space-between;\n"
        "            align-items: center;\n"
        "            flex-wrap: wrap;\n"
        "        }\n"
         ".botao-logout {\n"
        "  background: #e53935;\n"
        "  color: white;\n"
        "  padding: 0.4rem 0.8rem;\n"
        "  border: none;\n"
        "  border-radius: 6px;\n"
        "  font-size: 0.9rem;\n"
        "  font-weight: bold;\n"
        "  cursor: pointer;\n"
        "  transition: opacity 0.2s;\n"
        "  line-height: 1;\n"
        "  box-sizing: border-box;\n"
        "}\n"
        ".botao-logout:hover {\n"
        "  opacity: 0.9;\n"
        "}\n"
        ".lado-esquerdo {\n"
                "  display: flex;\n"
                "  align-items: center;\n"
                "  gap: 0.6rem;\n"
        "}\n"
        ".lado-esquerdo form {\n"
        "  display: contents;\n"
        "}\n"
        "        .marca {\n"
        "            font-size: 1.2rem;\n"
        "            font-weight: bold;\n"
        "        }\n"
        "        .menu-navegacao {\n"
        "            display: flex;\n"
        "            gap: 0.8rem;\n"
        "        }\n"
        "        .item-navegacao {\n"
        "            color: white;\n"
        "            text-decoration: none;\n"
        "            padding: 0.4rem 0.8rem;\n"
        "            border-radius: 4px;\n"
        "            font-size: 0.9rem;\n"
        "            transition: background-color 0.2s;\n"
        "        }\n"
        "        .item-navegacao:hover {\n"
        "            background-color: rgba(255, 255, 255, 0.1);\n"
        "        }\n"
        "        .conteudo-principal {\n"
        "            flex: 1;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            padding: 1rem;\n"
        "        }\n"
        "        .caixa {\n"
        "            width: 100%%;\n"
        "            max-width: 400px;\n"
        "            padding: 1.5rem;\n"
        "            background: white;\n"
        "            border-radius: 12px;\n"
        "            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n"
        "        }\n"
        "        .mensagem-erro {\n"
        "            background: #f44336;\n"
        "            color: white;\n"
        "            padding: 12px;\n"
        "            margin-bottom: 15px;\n"
        "            border-radius: 8px;\n"
        "            font-size: 0.9rem;\n"
        "        }\n"
        "        h1 {\n"
        "            color: #166088;\n"
        "            font-size: 1.3rem;\n"
        "            margin-bottom: 1.5rem;\n"
        "            text-align: center;\n"
        "        }\n"
        "        .form-group {\n"
        "            margin-bottom: 1.2rem;\n"
        "        }\n"
        "        label {\n"
        "            display: block;\n"
        "            margin-bottom: 0.5rem;\n"
        "            font-weight: 600;\n"
        "            color: #4a6fa5;\n"
        "        }\n"
        "        input[type=\"text\"], select {\n"
        "            width: 100%%;\n"
        "            padding: 0.8rem;\n"
        "            border: 2px solid #4a6fa5;\n"
        "            border-radius: 6px;\n"
        "            font-size: 1rem;\n"
        "            box-sizing: border-box;\n"
        "        }\n"
        "        .acoes {\n"
        "            display: flex;\n"
        "            justify-content: space-between;\n"
        "            margin-top: 1.5rem;\n"
        "            gap: 0.8rem;\n"
        "        }\n"
        "        .botao {\n"
        "            padding: 0.7rem 1rem;\n"
        "            border: none;\n"
        "            border-radius: 6px;\n"
        "            font-size: 0.9rem;\n"
        "            font-weight: 600;\n"
        "            cursor: pointer;\n"
        "            transition: all 0.2s;\n"
        "            flex: 1;\n"
        "            text-align: center;\n"
        "            text-decoration: none;\n"
        "        }\n"
        "        .botao-primario {\n"
        "            background: #4CAF50;\n"
        "            color: white;\n"
        "        }\n"
        "        .botao-secundario {\n"
        "            background: #f44336;\n"
        "            color: white;\n"
        "        }\n"
        "        .botao:hover {\n"
        "            opacity: 0.9;\n"
        "        }\n"
        "        @media (max-width: 480px) {\n"
        "            .caixa {\n"
        "                padding: 1rem;\n"
        "            }\n"
        "            input[type=\"text\"], select {\n"
        "                padding: 0.6rem;\n"
        "            }\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "<div class=\"container-administrador\">\n"
        "    <nav class=\"barra-navegacao\">\n"
        "<div class=\"lado-esquerdo\">\n"
        "  <form method=\"POST\" action=\"/logout\">\n"
        "    <button type=\"submit\" class=\"botao botao-logout\">Sair</button>\n"
        "  </form>\n"
        "  <div class=\"marca\">Cadastrar Usuário</div>\n"
        "</div>\n"
        "        <div class=\"menu-navegacao\">\n"
        "            <a href=\"/principal_admin\" class=\"item-navegacao\">Página Principal</a>\n"
        "        </div>\n"
        "    </nav>\n"
        "    <div class=\"conteudo-principal\">\n"
        "        <div class=\"caixa\">\n"
        "            <h1>Cadastrar Novo Usuário</h1>\n"
        "            %s\n"
        "            <form method=\"POST\" action=\"/cadastrar-usuario\">\n"
        "                <div class=\"form-group\">\n"
        "                    <label for=\"nome\">Nome:</label>\n"
        "                    <input type=\"text\" id=\"nome\" name=\"nome\" required>\n"
        "                </div>\n"
        "                <div class=\"form-group\">\n"
        "                    <label for=\"tipo\">Tipo:</label>\n"
        "                    <select id=\"tipo\" name=\"tipo\" required>\n"
        "                        <option value=\"\" disabled selected>Selecione o tipo</option>\n"
        "                        <option value=\"admin\">Administrador</option>\n"
        "                        <option value=\"comum\">Usuário Comum</option>\n"
        "                    </select>\n"
        "                </div>\n"
        "                <div class=\"form-group\">\n"
        "                    <label for=\"usuario\">Usuário:</label>\n"
        "                    <input type=\"text\" id=\"usuario\" name=\"usuario\" required>\n"
        "                </div>\n"
        "                <div class=\"form-group\">\n"
        "                    <label for=\"senha\">Senha:</label>\n"
        "                    <input type=\"text\" id=\"senha\" name=\"senha\" required>\n"
        "                </div>\n"
        "                <div class=\"acoes\">\n"
        "                    <button type=\"button\" class=\"botao botao-secundario\" onclick=\"limparCampos()\">Limpar</button>\n"
        "                    <button type=\"submit\" class=\"botao botao-primario\">Cadastrar</button>\n"
        "                </div>\n"
        "            </form>\n"
        "        </div>\n"
        "    </div>\n"
        "</div>\n"
        "<script>\n"
        "    function limparCampos() {\n"
        "        document.getElementById('nome').value = '';\n"
        "        document.getElementById('tipo').value = '';\n"
        "        document.getElementById('usuario').value = '';\n"
        "        document.getElementById('senha').value = '';\n"
        "    }\n"
        "</script>\n"
        "</body>\n"
        "</html>\n",
        bloco_erro  
    );
}
