#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include "lwip/pbuf.h"
#include "lwip/tcp.h"
#include "login.h"

extern char http_response[8192];
   
// Cria a página de login
void create_login_page(const char *mensagem_erro) {
     char bloco_erro[256] = "";

        if (mensagem_erro && strlen(mensagem_erro) > 0) {
            snprintf(bloco_erro, sizeof(bloco_erro),
                    "<div class=\"mensagem-erro\">%s</div>", mensagem_erro);
        }
        
    snprintf(http_response, sizeof(http_response),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=UTF-8\r\n\r\n"
        "<!DOCTYPE html>"
        "<html lang=\"pt-BR\">"
        "<head>"
        "<meta charset=\"UTF-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "<title>Login - Fechadura Eletrônica</title>"
        "<style>"
        "body {"
        "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
        "  background: linear-gradient(135deg, #f5f7fa 0%%, #c3cfe2 100%%);"
        "  margin: 0;"
        "  padding: 0;"
        "  display: flex;"
        "  justify-content: center;"
        "  align-items: center;"
        "  min-height: 100vh;"
        "  color: #333333;"
        "}"
        ".caixa-login {"
        "  width: 100%%;"
        "  max-width: 400px;"
        "  padding: 2rem;"
        "  background: #ffffff;"
        "  border-radius: 16px;"
        "  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);"
        "  text-align: center;"
        "}"
        "h2 {"
        "  color: #166088;"
        "  margin-bottom: 2rem;"
        "  text-align: center;"
        "  width: 100%%;"
        "}"
        "input[type=text], input[type=password] {"
        "  width: 100%%;"
        "  padding: 15px;"
        "  margin: 10px 0;"
        "  border: 2px solid #dddddd;"
        "  border-radius: 8px;"
        "  font-size: 1rem;"
        "  box-sizing: border-box;"
        "}"
        "input[type=text]:focus, input[type=password]:focus {"
        "  border-color: #4a6fa5;"
        "  outline: none;"
        "}"
        ".botao-login {"
        "  width: 100%%;"
        "  padding: 15px;"
        "  background: #4CAF50;"
        "  border: none;"
        "  border-radius: 8px;"
        "  color: #ffffff;"
        "  font-size: 1rem;"
        "  font-weight: 600;"
        "  cursor: pointer;"
        "  margin-top: 20px;"
        "  transition: all 0.2s;"
        "}"
        ".botao-login:hover {"
        "  opacity: 0.9;"
        "  transform: translateY(-2px);"
        "}"
        ".botao-login:active {"
        "  transform: translateY(0);"
        "}"
        ".mensagem-erro {"
        "  background: #f44336;"
        "  color: #ffffff;"
        "  padding: 12px;"
        "  margin: 15px 0;"
        "  border-radius: 8px;"
        "  text-align: center;"
        "  font-size: 0.9rem;"
        "}"
        "@media (max-width: 480px) {"
        "  .caixa-login {"
        "    padding: 1.5rem;"
        "    margin: 1rem;"
        "  }"
        "  input[type=text], input[type=password] {"
        "    padding: 12px;"
        "  }"
        "  .botao-login {"
        "    padding: 12px;"
        "  }"
        "}"
        "</style>"
        "</head>"
        "<body>"
        "<div class=\"caixa-login\">"
        "<h2>Login</h2>"
        "%s"
        "<form method=\"POST\" action=\"/login\">"
        "<input type=\"text\" name=\"username\" placeholder=\"Usuário\" required>"
        "<input type=\"password\" name=\"password\" placeholder=\"Senha\" required>"
        "<button type=\"submit\" class=\"botao-login\">Entrar</button>"
        "</form>"
        "</div>"
        "<script>"
        "document.cookie = \"session=; Path=/; Max-Age=0\";\n"
        "document.cookie = \"nome=; Path=/; Max-Age=0\";\n"
        "document.cookie = \"tipo=; Path=/; Max-Age=0\";\n"
        "</script>"
        "</body>"
        "</html>",
        bloco_erro  
    );
}
